### ISSUE TITLE
Import pipeline for Macauff association table

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/hipscat-import#147]
## Pipeline description

Copied from [design doc](https://docs.google.com/document/d/14HXjrVQT-9I6BNWOrZ0yHyiIHdn1iArykobHAIxbBdw/edit)

Create a dedicated map-reduce pipeline within the hipscat-import pipeline structure.

- read the XML file, and create a new parquet metadata file from it
- for each input file / chunk
  - fetch left catalog partition info
  - fetch right catalog partition info
  - map left and right to healpix
  - split to match left partitions
     - include all columns, including likelihood scores
     - write to sharded parquet using generated parquet metadata
- for each left partition
  - aggregate sharded files
- write metadata files

## Milestones

- [x] Pipeline boilerplate ([see similar PR](https://github.com/astronomy-commons/hipscat-import/pull/126))
- [x] Test data files (XML and CSV)
- [ ] Pipeline map reduce
